pipeline {

  agent {
    label 'sbt-slave'
  }

  stages {
    stage('Compile') {
      steps {
        ansiColor('xterm') {
          script {
            sh "sbt clean compile doc"
          }
        }
      }
    }

    stage('Test') {
      steps {
        ansiColor('xterm') {
          script {
            sh "sbt coverage test coverageReport"
            junit '**/test-reports/*.xml'
          }
        }
      }
    }

    stage('IntegrationTest') {
      steps {
        ansiColor('xterm') {
          script {
            def dockerip = sh(returnStdout: true, script:  \$/wget http://169.254.169.254/latest/meta-data/local-ipv4 -qO-/\$).trim()
            withEnv(["APP_HOST=\$dockerip"]) {
              sh "sbt integrationTests"
              junit '**/test-reports/*.xml'
            }
          }
        }
      }
    }
  }
}
